name: pipeline-CI
run-name: First pipeline in github action

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Roda um hello ai dog
        run: echo "Rodou"
